language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1_Kornev_AllLabs
  - make -j
  - ./StackTest/StackTest
  #- ./Stack/Stack
  # 111111111
  - ./QueueTest/QueueTest
  #- ./Queue/Queue
  - ./VectorTest/VectorTest
  #- ./Vector/Vector    
  - ./MatrixTest/MatrixTest
  #- ./Matrix/Matrix   
  - ./ListTest/ListTest
  #- ./List/List
  - ./ArrayListTest/ArrayListTest
  #- ./ArrayListTest/ArrayList
  - ./MultiStackTest/MultiStackTest
  #- ./MultiStack/MultiStack
  - ./PolinomialTest/PolinomialTest
  #- ./PolinomialTest/Polinomial
  - ./RPNTest/RPNTest  
  #- ./RPNTest/RPN
  #- ./TextTest/TextTest
  #- ./Text/Text
  - ./ScanTableTest/ScanTableTest
  #- ./ScanTable/ScanTable
  - ./SortTableTest/SortTableTest
  #- ./SortTable/SortTable
  - ./TreeTableTest/TreeTableTest
  #- ./TreeTable/TreeTable
  - ./HashTableTest/HashTableTest
  #- ./HashTable/HashTable
  
notifications:
  email: false
